#!/bin/bash

NAME="sysdocker"
exec docker run --rm --name "$NAME" \
    --tmpfs /tmp --tmpfs /run --tmpfs /run/lock \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -p 2222:22 \
    cjalmeida/sysdocker